Adding sms provider SMSGlobal
nextcloud/twofactor_gateway pull request #457
Opened 2021-07-09 14:22 UTC by bosdla

Hi guys,
I've added SMSGlobal.com as 2fa SMS Provider. (similar to playSMS) 

Can you please integrate this into the main version?
thanks you
Bosdla

2021-07-14 11:07 UTC, ChristophWurst commented
@seyfahni @j-ed @boppy @fblackburn1 @kimsyversen could you help review this? :)

2021-07-14 11:08 UTC, ChristophWurst commented on lib/Service/Gateway/SMS/Provider/SMSGlobalConfig.php
> + * @author Christoph Wurst <christoph@winzerhof-wurst.at>
it wasn't me :-)

2021-07-14 11:08 UTC, ChristophWurst commented on lib/Service/Gateway/SMS/Provider/SMSGlobal.php
> + * @author Pascal Clémot <pascal.clemot@free.fr>
I don't think so

2021-07-19 16:14 UTC, boppy requested changes

2021-07-19 16:14 UTC, boppy commented on doc/Admin Documentation.md
> +Use the Webservices provided by playSMS for sending SMS.
Please Change name here.

2021-07-19 16:14 UTC, boppy commented on lib/Service/Gateway/SMS/Provider/SMSGlobal.php
> +                $to=str_replace("+", "", $identifier);
Please keep `\t` indentation.

2021-07-19 16:14 UTC, boppy commented on lib/Command/Configure.php
> +				$url='https://api.smsglobal.com/http-api.php';
Since this is not meant to be configured, you could hard-code it...

2021-07-28 14:50 UTC, boppy commented on lib/Service/Gateway/SMS/Provider/SMSGlobal.php
> +                $to=str_replace("+", "", $identifier);
Still not a `\t` after fix...

2021-07-28 14:51 UTC, boppy requested changes

2021-07-28 14:51 UTC, boppy commented on lib/Service/Gateway/SMS/Provider/SMSGlobal.php
> +        $to=str_replace("+", "", $identifier);
Still not a `\t` after fix...

2022-05-06 14:55 UTC, merged